version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  server:
    build: .
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql
      - MYSQLUSER=root
      - MYSQLPASS=example
      - TZ=America/Chicago
    volumes:
      - ./server/static:/app/static
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy
  pandoc:
    build: ./docs
    volumes:
      - ./docs:/data
    profiles:
      - mkdocs
